### ISSUE TITLE
Not starting after upgrading to Notebook 5.0

### ISSUE THREAD

**Issue by mpekalski** [jupyterhub/jupyterhub#1075]
I am running 
- JupyterHub 0.7.0dev
- on Docker 1.12.6 
- with Notebook  4.3.1

I wanted to upgrade to the latest Notebook 5.0. After doing so, I can see changes in the Notebook UI, but when I stop and remove the docker container and try to start it again it fails to start. 
the UI gives error message

> 500 : Internal Server Error
Spawner failed to start [status=ExitCode=1, Error='', FinishedAt=2017-04-12T08:37:34.271587492Z]

and the logs of docker tell something more detailed about jupyterhub-singleuser. 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 297, in <module>
    main()
  File "/opt/conda/bin/jupyterhub-singleuser", line 293, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/opt/conda/bin/jupyterhub-singleuser", line 268, in init_webapp
    super(SingleUserNotebookApp, self).init_webapp()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 220, in init_settings
    static_custom_path=jupyter_app.static_custom_path,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/bin/jupyterhub-singleuser", line 239, in _static_custom_path_default
    path = super(SingleUserNotebookApp, self)._static_custom_path_default()
AttributeError: 'super' object has no attribute '_static_custom_path_default'
user@machine:/volumes/user/{username}$ docker logs  jupyter-{username}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'static_custom_path'
```

Troubleshoot from within the container:
```
$PATH:
        /opt/conda/bin
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/lib/jvm/java/jre/bin

sys.path:
        /opt/conda/bin
        /usr/local/spark/python
        /usr/local/spark/python/lib/py4j-0.10.1-src.zip
        /opt/conda/lib/python35.zip
        /opt/conda/lib/python3.5
        /opt/conda/lib/python3.5/plat-linux
        /opt/conda/lib/python3.5/lib-dynload
        /opt/conda/lib/python3.5/site-packages
        /opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg

sys.executable:
        /opt/conda/bin/python

sys.version:
        3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
        [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

platform.platform():
        Linux-4.4.0-67-generic-x86_64-with-debian-8.6

which -a jupyter:
        /opt/conda/bin/jupyter
        /opt/conda/bin/jupyter

pip list:
        alabaster (0.7.9)
        appdirs (1.4.0)
        Babel (2.3.4)
        backports.shutil-get-terminal-size (1.0.0)
        beautifulsoup4 (4.5.3)
        bokeh (0.12.4)
        boto (2.45.0)
        brewer2mpl (1.4.1)
        bz2file (0.98)
        cairocffi (0.7.2)
        CairoSVG (2.0.1)
        certifi (2017.1.23)
        cffi (1.9.1)
        chardet (2.3.0)
        cloudpickle (0.2.2)
        colorlover (0.2.1)
        CommonMark (0.5.4)
        conda (4.3.8)
        conda-build (2.1.1)
        conda-verify (2.0.0)
        cryptography (1.7.1)
        cssselect (1.0.1)
        cufflinks (0.8.2)
        cycler (0.10.0)
        Cython (0.25.2)
        decorator (4.0.11)
        dill (0.2.5)
        docutils (0.13.1)
        dota2api (1.3.2)
        elasticsearch (5.2.0)
        fastcache (1.0.2)
        fastparquet (0.0.4.post1)
        filelock (2.0.7)
        future (0.16.0)
        gensim (0.13.4.1)
        ggplot (0.11.5)
        Ghost.py (0.2.3)
        h5py (2.6.0)
        hide-code (0.3.1)
        idna (2.2)
        imagesize (0.7.1)
        ipykernel (4.5.2)
        ipython (5.1.0)
        ipython-genutils (0.1.0)
        ipywidgets (5.2.2)
        Jinja2 (2.9.4)
        joblib (0.10.3)
        jsonschema (2.5.1)
        jupyter (1.0.0)
        jupyter-client (4.4.0)
        jupyter-console (5.0.0)
        jupyter-contrib-core (0.3.0)
        jupyter-contrib-nbextensions (0.2.3)
        jupyter-core (4.2.1)
        jupyter-highlight-selected-word (0.0.7)
        jupyter-latex-envs (1.3.6)
        jupyter-nbextensions-configurator (0.2.3)
        jupyter-themer (0.3.0)
        jupyterhub (0.5.0)
        jupyterthemes (0.13.9)
        lesscpy (0.12.0)
        Lifetimes (0.6.0.0)
        llvmlite (0.15.0)
        lxml (3.7.2)
        MarkupSafe (0.23)
        matplotlib (2.0.0)
        metakernel (0.18.4)
        mistune (0.7.3)
        mpmath (0.19)
        nb-config-manager (0.1.3)
        nbbrowserpdf (0.2.1)
        nbconvert (4.2.0)
        nbformat (4.2.0)
        nbsphinx (0.2.12)
        networkx (1.11)
        notebook (5.0.0)
        numba (0.30.1)
        numexpr (2.6.1)
        numpy (1.12.0)
        numpydoc (0.6.0)
        octave-kernel (0.24.5)
        packaging (16.8)
        pamela (0.2.1)
        pandas (0.19.2)
        parquet (1.1)
        patsy (0.4.1)
        pdfkit (0.6.1)
        pexpect (4.2.1)
        pickleshare (0.7.4)
        Pillow (3.4.2)
        pip (9.0.1)
        pkginfo (1.4.1)
        plotly (1.13.0)
        ply (3.9)
        pprint (0.1)
        prompt-toolkit (1.0.9)
        protobuf (3.0.0b2)
        psutil (5.0.1)
        psycopg2 (2.6.2)
        ptyprocess (0.5.1)
        py (1.4.31)
        pyasn1 (0.1.9)
        pycosat (0.6.1)
        pycparser (2.17)
        pycrypto (2.6.1)
        Pygments (2.1.3)
        PyHive (0.2.1)
        pymc3 (3.0)
        PyMySQL (0.7.9)
        pyOpenSSL (16.2.0)
        pyparsing (2.1.10)
        PyPDF2 (1.25.1)
        pyquery (1.2.17)
        pytest (3.0.6)
        python-dateutil (2.6.0)
        python-snappy (0.5)
        pytz (2016.10)
        PyYAML (3.12)
        pyzmq (16.0.2)
        qtconsole (4.2.1)
        recommonmark (0.4.0)
        requests (2.12.4)
        rpy2 (2.8.5)
        scikit-image (0.12.3)
        scikit-learn (0.18.1)
        scipy (0.18.1)
        seaborn (0.7.1)
        setuptools (34.0.2)
        simplegeneric (0.8.1)
        simplejson (3.10.0)
        six (1.10.0)
        skflow (0.1.0)
        sklearn (0.0)
        smart-open (1.3.5)
        snowballstemmer (1.2.1)
        Sphinx (1.5.2)
        SQLAlchemy (1.1.5)
        sqlalchemy-vertica-python (0.1.2)
        statsmodels (0.6.1)
        stomp.py (4.1.15)
        sympy (1.0)
        tensorflow (0.10.0)
        terminado (0.6)
        Theano (0.8.2)
        thriftpy (0.3.9)
        tinycss (0.4)
        tinydb (3.2.2)
        toree (0.1.0.dev7)
        tornado (4.4.2)
        tqdm (4.11.2)
        traitlets (4.3.1)
        urllib3 (1.20)
        vertica-python (0.6.11)
        wcwidth (0.1.7)
        wheel (0.29.0)
        widgetsnbextension (1.2.6)
        yapf (0.15.1)

conda list:
        # packages in environment at /opt/conda:
        #
        alabaster                 0.7.9                     <pip>
        appdirs                   1.4.0                     <pip>
        Babel                     2.3.4                     <pip>
        backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
        beautifulsoup4            4.5.3                    py35_0
        blas                      1.1                    openblas    conda-forge
        bokeh                     0.12.4                   py35_0
        boto                      2.45.0                   py35_0
        brewer2mpl                1.4.1                     <pip>
        bz2file                   0.98                     py35_0
        bzip2                     1.0.6                         3
        cairo                     1.14.8                        0
        cairocffi                 0.7.2                     <pip>
        CairoSVG                  2.0.1                     <pip>
        certifi                   2017.1.23                 <pip>
        cffi                      1.9.1                    py35_0
        chardet                   2.3.0                    py35_0
        cloog                     0.18.0                        0
        cloudpickle               0.2.2                    py35_0
        colorlover                0.2.1                     <pip>
        CommonMark                0.5.4                     <pip>
        conda                     4.3.8                    py35_0
        conda-build               2.1.1                    py35_0
        conda-env                 2.6.0                         0
        conda-verify              2.0.0                    py35_0
        cryptography              1.7.1                    py35_0
        cssselect                 1.0.1                     <pip>
        cufflinks                 0.8.2                     <pip>
        curl                      7.49.0                        1
        cycler                    0.10.0                   py35_0
        cython                    0.25.2                   py35_0
        dbus                      1.10.10                       0
        decorator                 4.0.11                   py35_0
        dill                      0.2.5                    py35_0
        docutils                  0.13.1                    <pip>
        dota2api                  1.3.2                     <pip>
        elasticsearch             5.2.0                     <pip>
        entrypoints               0.2.2                    py35_0
        expat                     2.1.0                         0
        fastcache                 1.0.2                    py35_1
        fastparquet               0.0.4post1               py35_0    conda-forge
        filelock                  2.0.7                    py35_0
        fontconfig                2.12.1                        2
        freetype                  2.5.5                         2
        future                    0.16.0                    <pip>
        gcc                       4.8.5                         7
        gensim                    0.13.4.1            np111py35_0
        ggplot                    0.11.5                    <pip>
        ghost.py                  0.2.3                    py35_0    anaconda-nb-extensions
        glib                      2.50.2                        1
        gmp                       6.1.0                         0
        gsl                       1.16                          1    r
        gst-plugins-base          1.8.0                         0
        gstreamer                 1.8.0                         0
        h5py                      2.6.0               np111py35_2
        harfbuzz                  0.9.35                        6    r
        hdf5                      1.8.17                        1
        hide-code                 0.3.1                     <pip>
        icu                       54.1                          0
        idna                      2.2                      py35_0
        imagesize                 0.7.1                     <pip>
        ipykernel                 4.5.2                    py35_0
        ipython                   5.1.0                    py35_0
        ipython_genutils          0.1.0                    py35_0
        ipywidgets                5.2.2                    py35_1
        isl                       0.12.2                        0
        jbig                      2.1                           0
        jinja2                    2.9.4                    py35_0
        joblib                    0.10.3                    <pip>
        joblib                    0.10.3                   py35_0    conda-forge
        jpeg                      8d                            2
        jsonschema                2.5.1                    py35_0
        jupyter                   1.0.0                    py35_3
        jupyter-contrib-nbextensions 0.2.3                     <pip>
        jupyter-highlight-selected-word 0.0.7                     <pip>
        jupyter-latex-envs        1.3.6                     <pip>
        jupyter-themer            0.3.0                     <pip>
        jupyter_client            4.4.0                    py35_0
        jupyter_console           5.0.0                    py35_0
        jupyter_contrib_core      0.3.0                    py35_1    conda-forge
        jupyter_core              4.2.1                    py35_0
        jupyter_nbextensions_configurator 0.2.3                    py35_0    conda-forge
        jupyterhub                0.5.0                     <pip>
        jupyterthemes             0.13.9                    <pip>
        lesscpy                   0.12.0                    <pip>
        libffi                    3.2.1                         1
        libgcc                    5.2.0                         0
        libgfortran               3.0.0                         1
        libiconv                  1.14                          0
        libpng                    1.6.27                        0
        libpq                     9.5.4                         0
        libsodium                 1.0.10                        0
        libtiff                   4.0.6                         2
        libxcb                    1.12                          1
        libxml2                   2.9.4                         0
        libxslt                   1.1.29                        0
        Lifetimes                 0.6.0.0                   <pip>
        llvmlite                  0.15.0                   py35_0
        lxml                      3.7.2                    py35_0
        markupsafe                0.23                     py35_2
        matplotlib                2.0.0               np111py35_0
        metakernel                0.18.4                    <pip>
        mistune                   0.7.3                    py35_0
        mpc                       1.0.3                         0
        mpfr                      3.1.5                         0
        mpmath                    0.19                     py35_1
        nb_config_manager         0.1.3                    py35_0    anaconda-nb-extensions
        nbbrowserpdf              0.2.2                    py35_0    anaconda-nb-extensions
        nbconvert                 4.2.0                    py35_0
        nbformat                  4.2.0                    py35_0
        nbsphinx                  0.2.12                    <pip>
        ncurses                   5.9                           8    r
        networkx                  1.11                     py35_0
        nomkl                     1.0                           0
        notebook                  5.0.0                    py35_0
        numba                     0.30.1              np111py35_0
        numexpr                   2.6.1           np111py35_nomkl_2  [nomkl]
        numpy                     1.11.3             py35_nomkl_0  [nomkl]
        numpy                     1.12.0                    <pip>
        numpydoc                  0.6.0                     <pip>
        octave-kernel             0.24.5                    <pip>
        openblas                  0.2.19                        0
        openssl                   1.0.2j                        0
        packaging                 16.8                      <pip>
        pamela                    0.2.1                     <pip>
        pandas                    0.19.2              np111py35_1
        pango                     1.40.3                        1
        parquet                   1.1                       <pip>
        patchelf                  0.9                           0
        path.py                   10.0                     py35_0
        patsy                     0.4.1                    py35_0
        pcre                      8.39                          1
        pdfkit                    0.6.1                     <pip>
        pexpect                   4.2.1                    py35_0
        pickleshare               0.7.4                    py35_0
        pillow                    3.4.2                    py35_0
        pip                       9.0.1                    py35_1
        pixman                    0.34.0                        0
        pkginfo                   1.4.1                    py35_0
        plotly                    1.13.0                    <pip>
        plotly                    1.12.9                   py35_0
        ply                       3.9                      py35_0    conda-forge
        pprint                    0.1                       <pip>
        prompt_toolkit            1.0.9                    py35_0
        protobuf                  3.0.0b2                   <pip>
        psutil                    5.0.1                     <pip>
        psycopg2                  2.6.2                    py35_0
        ptyprocess                0.5.1                    py35_0
        py                        1.4.31                   py35_0    conda-forge
        pyasn1                    0.1.9                    py35_0
        pycosat                   0.6.1                    py35_1
        pycparser                 2.17                     py35_0
        pycrypto                  2.6.1                    py35_4
        pygments                  2.1.3                    py35_0
        PyHive                    0.2.1                     <pip>
        pymc3                     3.0                       <pip>
        pymc3                     3.0                      py35_0    conda-forge
        pymysql                   0.7.9                    py35_0
        pyopenssl                 16.2.0                   py35_0
        pyparsing                 2.1.10                    <pip>
        pyparsing                 2.1.4                    py35_0
        pypdf2                    1.25.1                   py35_0    anaconda-nb-extensions
        pyqt                      5.6.0                    py35_2
        pyquery                   1.2.17                    <pip>
        pytest                    3.0.6                    py35_0    conda-forge
        python                    3.5.2                         0
        python-dateutil           2.6.0                    py35_0
        python-snappy             0.5                       <pip>
        pytz                      2016.10                  py35_0
        pyyaml                    3.12                     py35_0
        pyzmq                     16.0.2                   py35_0
        qt                        5.6.2                         2
        qtconsole                 4.2.1                    py35_1
        r-assertthat              0.1                    r3.3.2_4    r
        r-base                    3.3.2                         0    r
        r-base64enc               0.1_3                  r3.3.2_0    r
        r-bitops                  1.0_6                  r3.3.2_2    r
        r-colorspace              1.3_1                  r3.3.2_0    r
        r-crayon                  1.3.2                  r3.3.2_0    r
        r-dichromat               2.0_0                  r3.3.2_2    r
        r-digest                  0.6.10                 r3.3.2_0    r
        r-evaluate                0.10                   r3.3.2_0    r
        r-ggplot2                 2.2.0                  r3.3.2_0    r
        r-gtable                  0.2.0                  r3.3.2_0    r
        r-irdisplay               0.4.4                  r3.3.2_0    r
        r-irkernel                0.7.1                  r3.3.2_0    r
        r-jsonlite                1.1                    r3.3.2_0    r
        r-labeling                0.3                    r3.3.2_2    r
        r-lazyeval                0.2.0                  r3.3.2_0    r
        r-magrittr                1.5                    r3.3.2_2    r
        r-mass                    7.3_45                 r3.3.2_0    r
        r-memoise                 1.0.0                  r3.3.2_0    r
        r-munsell                 0.4.3                  r3.3.2_0    r
        r-pbdzmq                  0.2_4                  r3.3.2_0    r
        r-plyr                    1.8.4                  r3.3.2_0    r
        r-r6                      2.2.0                  r3.3.2_0    r
        r-rcolorbrewer            1.1_2                  r3.3.2_3    r
        r-rcpp                    0.12.8                 r3.3.2_0    r
        r-rcurl                   1.95_4.8               r3.3.2_0    r
        r-repr                    0.10                   r3.3.2_0    r
        r-reshape2                1.4.2                  r3.3.2_0    r
        r-scales                  0.4.1                  r3.3.2_0    r
        r-stringi                 1.1.2                  r3.3.2_0    r
        r-stringr                 1.1.0                  r3.3.2_0    r
        r-tibble                  1.2                    r3.3.2_0    r
        r-uuid                    0.1_2                  r3.3.2_0    r
        readline                  6.2                           2
        recommonmark              0.4.0                     <pip>
        requests                  2.12.4                   py35_0
        rpy2                      2.8.5                     <pip>
        ruamel_yaml               0.11.14                  py35_1
        scikit-image              0.12.3              np111py35_1
        scikit-learn              0.18.1          np111py35_nomkl_1  [nomkl]
        scipy                     0.18.1          np111py35_nomkl_1  [nomkl]
        seaborn                   0.7.1                    py35_0
        setuptools                27.2.0                   py35_0
        setuptools                34.0.2                    <pip>
        simplegeneric             0.8.1                    py35_1
        simplejson                3.10.0                    <pip>
        sip                       4.18                     py35_0
        six                       1.10.0                    <pip>
        six                       1.10.0                   py35_0
        skflow                    0.1.0                     <pip>
        sklearn                   0.0                       <pip>
        smart_open                1.3.5                    py35_0
        snowballstemmer           1.2.1                     <pip>
        Sphinx                    1.5.2                     <pip>
        SQLAlchemy                1.1.1                     <pip>
        sqlalchemy                1.1.5                    py35_0
        sqlalchemy-vertica-python 0.1.2                     <pip>
        sqlite                    3.13.0                        0
        statsmodels               0.6.1               np111py35_1
        stomp.py                  4.1.15                    <pip>
        sympy                     1.0                      py35_0
        tensorflow                0.10.0                    <pip>
        terminado                 0.6                      py35_0
        theano                    0.8.2                    py35_0    conda-forge
        thriftpy                  0.3.9                    py35_0    conda-forge
        tinycss                   0.4                       <pip>
        tinydb                    3.2.2                     <pip>
        tinydb                    3.2.0                    py35_0    conda-forge
        tk                        8.5.18                        0
        toree                     0.1.0.dev7                <pip>
        tornado                   4.4.2                    py35_0
        tqdm                      4.11.1                   py35_1    conda-forge
        tqdm                      4.11.2                    <pip>
        traitlets                 4.3.1                    py35_0
        urllib3                   1.20                      <pip>
        vertica-python            0.6.11                    <pip>
        wcwidth                   0.1.7                    py35_0
        wheel                     0.29.0                   py35_0
        widgetsnbextension        1.2.6                    py35_0
        xz                        5.2.2                         1
        yaml                      0.1.6                         0
        yapf                      0.15.1                    <pip>
        zeromq                    4.1.5                         0
        zlib                      1.2.8                         3
```

**Comment by minrk** [comment]
> JupyterHub 0.7.0dev

Looks like you are using an old development version of JupyterHub. I believe this was fixed in JupyterHub 0.7.0. I would recommend upgrading to JupyterHub 0.7.2, the current stable version.

**Comment by mpekalski** [comment]
Unfortunately it looks like it was not fixed. I have updated to the latest 0.7.2 (from git), but the error is still there.

```
$ /usr/local/bin/jupyterhub  --version
0.7.2
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 297, in <module>
    main()
  File "/opt/conda/bin/jupyterhub-singleuser", line 293, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/opt/conda/bin/jupyterhub-singleuser", line 268, in init_webapp
    super(SingleUserNotebookApp, self).init_webapp()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 220, in init_settings
    static_custom_path=jupyter_app.static_custom_path,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/bin/jupyterhub-singleuser", line 239, in _static_custom_path_default
    path = super(SingleUserNotebookApp, self)._static_custom_path_default()
AttributeError: 'super' object has no attribute '_static_custom_path_default'
```

**Comment by mpekalski** [comment]
If I understand correctly the latest version 

https://github.com/jupyterhub/jupyterhub/blob/703ed7d21ef822d0dbde4b91c1dd7b2ccabee188/jupyterhub/singleuser.py

does not have `_static_custom_path_default`, so the problem is with spawner, right?

**Comment by willingc** [comment]
Hi @mpekalski, Sorry for the delay. Several of us are on holiday vacation. Would you be able to share the output of the original exception that caused the second exception? Thanks!

**Comment by mpekalski** [comment]
No worries. It is a popular holiday season. ;)
When I run `conda upgrade notebook` I get two packages upgraded
```
    gsl:      1.16-1       r --> 2.2.1-blas_openblas_2 conda-forge [blas_openblas]
    notebook: 4.3.1-py35_0   --> 5.0.0-py35_0
```

But coming back to logs. That is all I have from the docker image logs.
```
{username}@host_server:~$ docker logs jupyter-{username}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'static_custom_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 297, in <module>
    main()
  File "/opt/conda/bin/jupyterhub-singleuser", line 293, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/opt/conda/bin/jupyterhub-singleuser", line 268, in init_webapp
    super(SingleUserNotebookApp, self).init_webapp()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 220, in init_settings
    static_custom_path=jupyter_app.static_custom_path,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/bin/jupyterhub-singleuser", line 239, in _static_custom_path_default
    path = super(SingleUserNotebookApp, self)._static_custom_path_default()
AttributeError: 'super' object has no attribute '_static_custom_path_default'
{username}@host_server:~$ docker logs --tail 1000 jupyter-{username}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'static_custom_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 297, in <module>
    main()
  File "/opt/conda/bin/jupyterhub-singleuser", line 293, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/opt/conda/bin/jupyterhub-singleuser", line 268, in init_webapp
    super(SingleUserNotebookApp, self).init_webapp()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 220, in init_settings
    static_custom_path=jupyter_app.static_custom_path,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/bin/jupyterhub-singleuser", line 239, in _static_custom_path_default
    path = super(SingleUserNotebookApp, self)._static_custom_path_default()
AttributeError: 'super' object has no attribute '_static_custom_path_default'
{username}@host_server:~$

```

**Comment by minrk** [comment]
What's your base docker image? This is the key line in your container:

> `jupyterhub                0.5.0                     <pip>`

The jupyterhub package *in the image* needs to be upgraded. This could be because your image is based on a stale base image. Alternately, you could run:

    conda install jupyterhub=0.7

in container to get a compatible version of the jupyterhub-singleuser entrypoint.

**Comment by mpekalski** [comment]
The base image is `FROM jupyter/all-spark-notebook`

I upgraded the jupyterhub to 0.7.2 and notebook to 5.0 within the docker and now I get an error that 
`Running as root is not recommended. Use --allow-root to bypass.`

I added `c.NotebookApp.allow_root=True` to jupyterhub_config.py but it does not help.

**Comment by minrk** [comment]
> I added c.NotebookApp.allow_root=True to jupyterhub_config.py but it does not help.

This would go in `jupyter_notebook_config.py` in the container, not jupyterhub_config.

**Comment by mpekalski** [comment]
It worked, thank You.

For those who will have to add it in the future. I have home folders mapped to a storage outside of the docker, so by default each user should have its own config file. It is good to point to a notebook config file within the docker. For that I had to add path to a config file of a default docker user
`--config=/home/jovyan/.jupyter/jupyter_notebook_config.py`
to 
`/usr/local/bin/start-singleuser.sh`

**Comment by willingc** [comment]
Hi @mpekalski, I'm glad you got it working :smile:

If you would like, please feel free to submit a PR to the [FAQ](https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html) in the JupyterHub docs [doc source troubleshooting.md](https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/troubleshooting.md) with anything that you think would be helpful for folks in the future :sunny:
