### ISSUE TITLE
Jupyterhub + SAMP  + Javascript

### ISSUE THREAD

**Issue by joseQSR** [jupyterhub/jupyterhub#1151]
Hello everyone!
I apologize in advance but I have searched and I have not found a case similar to mine. I am trying to use the SAMP protocol, http://astrojs.github.io/sampjs/ in Jupyterhub. For example, I tried this example http://astrojs.github.io/sampjs/examples/send.html with the TOPCAT software http://www.star.bris.ac.uk/~mbt/topcat/ and this votable file http://andromeda.star.bris.ac.uk/data/ACE_data.vot. My source code is this:

```
%%html
<script type="text/javascript" src="samp.js"></script> 
<p id="demo">test</p>

<script>

document.getElementById("demo").addEventListener("click", myFunction);


function myFunction(connection) {
    var tableUrl = "resources/ACE_data.vot";
    document.getElementById("demo").innerHTML = "YOU CLICKED ME!";
    var msg = new samp.Message("table.load.votable", {"url": tableUrl});
      connection.notifyAll([msg]);
}
</script>
```

Any idea why it does not work?

**Comment by willingc** [comment]
Hi @joseQSR,

Sorry for the delayed response; the JupyterHub team has been traveling for developer meetings. I'm not familiar with samp.js. A few suggestions, as this issue is out of the scope of JupyterHub and would be better addressed by the Notebook developers:

- Get your code example running outside of the notebook
- Take a look at your URL definitions and make sure they are correct
- Take a look that the files are being loaded correctly with the right path
- Review the docs on `%%javascript`

Hope that helps you get started.

**Comment by joseQSR** [comment]
Hi @willingc ,
I have checked everything and it still does not work. Anyway, thanks for the advice! Should I post in the Jupyter Notebook forum my question?

**Comment by willingc** [comment]
Sure. Go ahead and try asking the question in the forum. Good luck @joseQSR :sunny:
