### ISSUE TITLE
User logout does not invalidate cookies for services

### ISSUE THREAD

**Issue by jhamrick** [jupyterhub/jupyterhub#1491]
It seems that if you log in as a user that has access to the server, and then logout, this does not invalidate the cookie or token for that service and so you can still gain access to it. This is an annoyance with testing, and potentially a security issue (if a user was using JupyterHub on a public machine).

**How to reproduce the issue**

1. Create a `jupyterhub_config.py` with a service, e.g.

```
c = get_config()

c.Authenticator.whitelist = [
    'instructor1'
]

c.JupyterHub.load_groups = {
    'formgrader-course101': [
        'instructor1'
    ]
}

c.JupyterHub.services = [
    {
        'name': 'course101',
        'url': 'http://127.0.0.1:9999',
        'command': [
            'jupyterhub-singleuser',
            '--group=formgrader-course101',
            '--debug',
        ],
        'user': 'grader-course101',
        'cwd': '/home/grader-course101'
    }
]
```

2. Go to the service url, e.g. `/services/course101`. Observe that you get redirected to the login page (good!).

3. Now log in as the user, and go to the service url. Observe you can access it.

4. Go back to the user's server, and click "log out". Go back to the service url and observe that you can still access it.

**What you expected to happen**

After the user logs out, they should no longer have access to the service.

**What actually happens**

After the user logs out, they still have access to the service.

**Share what version of JupyterHub you are using**

0.8.0

**Comment by minrk** [comment]
This is a consequence of the new OAuth setup.

When you login to something with OAuth, an OAuth token is allocated and stored in a cookie *set by the service*. So you have separate cookies set by each service/server you are logged in to. To properly logout of all of these, we would need to either:

1. somehow know all cookies of all services and clear them (easy for notebooks, hard in general), or
2. know which tokens have been allocated for this browser session and revoke them on logout.

I suspect we need to have a separate domain-wide, world-readable session id that we use purely to associate tokens with a browser session. With that, we should be able to revoke tokens.

**Comment by ogre0403** [comment]
@minrk  Is this bug fixed in 0.8.1 ? I still have similar problem when I use Github oauth.

**Comment by minrk** [comment]
@ogre0403 no, it will be fixed in 0.9.0

**Comment by lakshaykc** [comment]
@minrk I am using 0.9.4 on kubernetes cluster and still facing the same issue. I am using ```GenericOAuthenticator``` that uses login/logout of my application. When I logout of jupyterhub, I'm redirected to the _**Sign In with GenericOAuthenticator**_ page, but user cookies or token are still valid.

For example, if I logout of jupyterhub as well as my application, I don't expect to _Sign In_ to jupyterhub without entering logging in through my application. However, I am able to login to jupyterhub without entering my credentials. 

In the following hub log, user _**lakshay**_ logs out of the jupyterhub and the authenticating app. Then user _**test_user_2**_ logs in to the authenticating app. Jupyterhub still retains user _**lakshay**_'s token/ cookies. When user _**test_user_2**_ tries to _Sign In_ to jupyterhub, _**lakshay**_'s notebook server is opened i.e __notebooks.example.com/hub/user/lakshay/tree?__

```
[I 2019-06-24 19:00:45.983 JupyterHub login:19] User logged out: lakshay
[I 2019-06-24 19:00:46.001 JupyterHub log:158] 302 GET /hub/logout -> /hub/login (lakshay@10.24.0.1) 92.66ms
[I 2019-06-24 19:01:19.431 JupyterHub proxy:301] Checking routes
[I 2019-06-24 19:02:19.383 JupyterHub proxy:301] Checking routes
[I 2019-06-24 19:02:37.098 JupyterHub log:158] 302 GET /hub/user/test_user_2 -> /hub/login?next=%2Fhub%2Fuser%2Ftest_user_2 (@10.24.0.1) 1.34ms
[I 2019-06-24 19:02:37.397 JupyterHub log:158] 200 GET /hub/login?next=%2Fhub%2Fuser%2Ftest_user_2 (@10.24.0.1) 1.85ms
[I 2019-06-24 19:02:49.131 JupyterHub oauth2:82] OAuth redirect: 'https://notebooks.example.com/hub/oauth_callback'
[I 2019-06-24 19:02:49.132 JupyterHub log:158] 302 GET /hub/oauth_login?next=%2Fhub%2Fuser%2Ftest_user_2 -> https://example.com/o/authorize/?response_type=code&redirect_uri=https%3A%2F%2Fnotebooks.example.com%2Fhub%2Foauth_callback&client_id=YF2YgTSjrcafiifph2vOsOFdspg27Tbv7fg7kaVK&state=[secret] (@10.24.0.1) 2.13ms
[I 2019-06-24 19:02:49.630 JupyterHub base:509] User logged in: lakshay
[I 2019-06-24 19:02:49.631 JupyterHub log:158] 302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /hub/user/test_user_2 (@10.24.0.1) 166.98ms
[I 2019-06-24 19:02:49.726 JupyterHub log:158] 302 GET /hub/user/test_user_2 -> /user/lakshay/ (lakshay@10.24.0.1) 52.41ms
[I 2019-06-24 19:02:49.905 JupyterHub log:158] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-lakshay&redirect_uri=%2Fuser%2Flakshay%2Foauth_callback&response_type=code&state=[secret] -> /user/lakshay/oauth_callback?code=[secret]&state=[secret] (lakshay@10.24.0.1) 28.02ms
[I 2019-06-24 19:02:49.985 JupyterHub log:158] 200 POST /hub/api/oauth2/token (lakshay@10.24.1.23) 27.78ms
[I 2019-06-24 19:02:50.019 JupyterHub log:158] 200 GET /hub/api/authorizations/token/[secret] (lakshay@10.24.1.23) 20.93ms
```

It seems like my application's OAuth server verifies the user __test_user_2__ but jupyterhub still sees __lakshay__ as the logged in user and opens it's notebook server.

Any ideas why this might be happening? #1577 is supposed to fix this.
