### ISSUE TITLE
Jupyter connection persist even after JH logout

### ISSUE THREAD

**Issue by jai11** [jupyterhub/jupyterhub#735]

**Comment by jai11** [comment]
login to JH , open notebooks in two three tabs and also the terminal.

logout from single tab and execute command on terminal and run the notebook cells.

ideally they should not have the connection to the system once user is logged out.

**Comment by minrk** [comment]
The single-user server caches the validity of cookies for a short time, I believe the default is five minutes. You can shorten this time by setting `c.SingleUserNotebookApp.cookie_cache_lifetime` to a smaller value (in seconds). However, I do not believe it will affect currently open websocket connections (terminal, kernel execution), only new connections. That is, for a notebook that is open when logout happens, saving the notebook will start to be rejected, but execution will continue to be allowed until the connection is lost.

I don't view this as a particularly serious issue, and I think implementing notification and forced logout as a push mechanism would be pretty complicated. If you want to be conservative about it, stopping the user's single-user server on logout would ensure any open connections are terminated and caches are cleared.

**Comment by jai11** [comment]
@minrk I tried to set c.SingleUserNotebookApp.cookie_cache_lifetime and check. Got the logs for clearing the cache. But still connection persist and I can run the notebooks. 

I think once logout at least webscoket connections should not get connect.

**Comment by jai11** [comment]
@minrk  I strongly believe it as defect , once user is logged out. It should not able to do any operations on opened notebook on other tabs.

**Comment by minrk** [comment]
@jai11 you are seeing *new* websocket connections established after you see that the cookie cache has been cleared? Those connections will be logged. Can you share your log files where you see connections that should not have been allowed? As described above, *already established* websocket connections, such as those for an open terminal or notebook, will remain open as they are only authenticated at connection time.

**Comment by jai11** [comment]
doing some r&d what you said .. will give you my feed back

**Comment by jai11** [comment]
@minrk  Can we do something for already authenticated connections , once user have logged out. 

Any key in config for that to check if user have logged out so time out the session.

**Comment by minrk** [comment]
There is no mechanism, presently. The only available action is restarting the single-user server.

**Comment by jai11** [comment]
The restart will be a manual process right ?

**Comment by jai11** [comment]
@minrk can we decrease auto logout time , if yes how can we?

**Comment by willingc** [comment]
I'm going to close as I believe this was addressed in https://github.com/jupyterhub/jupyterhub/pull/840.

**Comment by Ajay-Changulani** [comment]
hi - is this issue really resolved? I am using notebook v5 and still face this issue. Please advise!
